# Storage Class - storageclass.yml
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gluster-dyn
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: http://10.102.222.29:8080
  restauthenabled: "false"
  secretNamespace: "Default"
  secretName: "heketi-secret"
